Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1419540/explainable_deep_learning/a4_adaptation_to_a1/train.py", line 22, in <module>
    import datasets
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/datasets/__init__.py", line 22, in <module>
    from .arrow_dataset import Dataset
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 66, in <module>
    from .arrow_reader import ArrowReader
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/datasets/arrow_reader.py", line 30, in <module>
    from .download.download_config import DownloadConfig
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/datasets/download/__init__.py", line 10, in <module>
    from .streaming_download_manager import StreamingDownloadManager
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/datasets/download/streaming_download_manager.py", line 18, in <module>
    from aiohttp.client_exceptions import ClientError
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/aiohttp/client.py", line 59, in <module>
    from .client_reqrep import (
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/uufs/chpc.utah.edu/common/home/u1419540/miniconda3/envs/edl_hw3/lib/python3.11/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
